### ISSUE TITLE
Posters Are No Populating on Idle

### ISSUE THREAD

**Issue by Bboy486** [MattsShack/Plex-Movie-Poster-Display#9] opened 2020-11-05 15:55 UTC
I have the script (v2) working on an RPi4. If I start a video it shows the poster of that video. However, on idle I just get a blank screen. 

Coming Soon I have the newest selected. I am not sure what else I would need to do.

Additionally, below is feedback from use over a few days. 

1. Allow multiple Plex Client under Plex Client IP. I could be watching something on my phone while the kids watch on the TV.
2. Add the option for padding around the top and bottom text. Ex https://prnt.sc/ve4ayf

**Comment by ZeroCoolGOS** [comment] 2020-11-29 19:33
@Bboy486 
When you say on idle you get a blank screen.  Are you talking about when you have paused the video?

How long until it goes blank?
Is it on one specific client?

**Comment by Bboy486** [comment] 2020-11-29 19:50
Pause a video or nothing running have the same issue. I thought this script would randomly pull in art when there was no file running. That was what I was referencing. Right now I only see a poster when I play a file on plex. 

My server is on windows and I tested on a note10+, nvidia shields (2 of them) and Fire tablets. Same issue on all (and I do update the ip for the clients when testing).

**Comment by ZeroCoolGOS** [comment] 2020-11-29 20:01
If you have stopped the video it should provide random "Coming Soon" artwork, provided you have set your "Plex Movie Selections" field in the settings.  Leaving this field empty or invalid will render the poster blank when not playing a movie.

I have not been able to recreate a blank page when I have paused my videos.

**Comment by jeffreyswiggins** [comment] 2020-12-28 23:24
I am having this same issue.  Installed this on my PI 3B+ today and works great if a movie is playing on the client but once stopped it goes black and nothing shows.  I have 1 "library" or "plex movie section" listed to make sure I am not missing something and that is "Movies".   Also have an issue where I cannot make the "Coming Soon Top Section" and "Bottom Section" plus the "Now Showing Top Section" and "Bottom Section" display nothing.  Meaning I don't what to have Title, Tagline, Summary, so I choose Custom and make it blank.  Each time I set it to blank at least one of those fields reverts to the word "custom" which displays on the screen.  Just want the posters no words and the Coming Soon to work

**Comment by jeffreyswiggins** [comment] 2020-12-28 23:44
> 
> 
> I am having this same issue. Installed this on my PI 3B+ today and works great if a movie is playing on the client but once stopped it goes black and nothing shows. I have 1 "library" or "plex movie section" listed to make sure I am not missing something and that is "Movies". Also have an issue where I cannot make the "Coming Soon Top Section" and "Bottom Section" plus the "Now Showing Top Section" and "Bottom Section" display nothing. Meaning I don't what to have Title, Tagline, Summary, so I choose Custom and make it blank. Each time I set it to blank at least one of those fields reverts to the word "custom" which displays on the screen. Just want the posters no words and the Coming Soon to work

So i manually edited the config.php file and got "custom" text removed so that is fixed.  The Coming Soon does not work.

**Comment by ZeroCoolGOS** [comment] 2020-12-29 01:30
@jeffreyswiggins how old is your build of Poster display?
There was an issue with the Coming Soon and Now Playing custom fields being improperly referenced and that should have been addressed within the last month or so as part of the dev branch.  Maybe give that branch a try and let us know if you still have the issue.

I will give the blank "Coming Soon" text a try as well.

Also if you can maybe provide a copy of the config file that you are having the issue with so we can help review.  Please scrub your Plex Token pre posting it.

**UPDATE:**
I have tested it and I can get my "Coming Soon" to show just the poster and no text and just setting the text to blank on the admin page.

**Comment by Bboy486** [comment] 2020-12-29 02:19
@ZeroCoolGOS Please also look into the blank screen on idle issue. Since @jeffreyswiggins has the same issue let's make sure we address that as it was my OP.

**Comment by ZeroCoolGOS** [comment] 2020-12-29 02:24
> @ZeroCoolGOS Please also look into the blank screen on idle issue. Since @jeffreyswiggins has the same issue let's make sure we address that as it was my OP. 
> 
> 
> 
> 

Can you also please provide a copy of your config file for review as well?

**Comment by jeffreyswiggins** [comment] 2020-12-29 11:58
So i reloaded with the DEV branch and it does seem more updated however I get the same results for Coming Soon.  My Sections in Plex are pretty straight Forward "Movies" and "TV Shows", but even with just "Movies" nothing shows up sp maybe I am missing something.

Also with the MASTER version the movie poster image shows up but with this DEV version it just says NOW SHOWING and **no movie poster** when something is playing on the client.  

Attached is the config

[config.txt](https://github.com/MattsShack/Plex-Movie-Poster-Display/files/5750591/config.txt)

**Comment by jeffreyswiggins** [comment] 2020-12-29 11:58
<?php
//PMPD Configuration
$pmpConfigVersion = '2';
$pmpUsername = 'admin';
$pmpPassword = 'vaRiaX6baSs';
$pmpClearImageCache = 'Yes'; //Default Yes
$pmpImageSpeed = '30'; //Default 30 Seconds
$pmpPosterDir = 'cache/posters/'; //Default cache/posters/ (FUTURE)
$pmpCustomDir = 'cache/custom/'; //Default cache/custom/ (FUTURE)

//Server Configuration
$plexServer = '10.0.0.41';
$plexToken = 'yPxJcf8q3Hrc17XhQ44y';
$plexServerMovieSection = 'Movies,TV Shows';
$cacheEnabled = '1'; //Default true

//Client Configuration
$plexClient = '10.0.0.68';
$plexClientName = 'Plex Web';

//Custom Image Configuration
$customImageEnabled = 'Disabled'; //Default: Disabled
$customImage = '';
$customTopText = '';
$customTopFontSize = '55'; //Default: 55 (px)
$customTopFontColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$customTopFontOutlineSize = '2'; //Default: 2 (px)
$customTopFontOutlineColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$customBottomText = '';
$customBottomFontSize = '25'; //Default: 25 (px)
$customBottomFontColor = '#FFFFFF'; //Default: #FFFFFF (White)
$customBottomFontOutlineSize = '2'; //Default: 2 (px)
$customBottomFontOutlineColor = '#FFFF00'; //Default: #FFFF00 (Yellow)

//Coming Soon Configuration
$comingSoonTop = 'custom'; //Default: custom (title/summary/tagline/custom)
$comingSoonTopAutoScale = ''; //Default: false
$comingSoonTopText = 'COMING SOON';
$comingSoonTopFontSize = '55'; //Default: 55 (px)
$comingSoonTopFontColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$comingSoonTopFontOutlineSize = '2'; //Default: 2 (px)
$comingSoonTopFontOutlineColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$showComingSoonInfo = ''; //Default: false
$comingSoonBottom = 'custom'; //Default: custom (title/summary/tagline/custom)
$comingSoonBottomText = 'Wiggins Media';
$comingSoonBottomAutoScale = ''; //Default: false
$comingSoonBottomFontSize = '25'; //Default: 25 (px)
$comingSoonBottomFontColor = '#FFFFFF'; //Default: #FFFFFF (White)
$comingSoonBottomFontOutlineSize = '2'; //Default: 2 (px)
$comingSoonBottomFontOutlineColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$comingSoonShowSelection = 'unwatched'; //Default: unwatched

//Now Showing Configuration
$nowShowingTop = 'custom'; //Default: custom (title/summary/tagline/custom)
$nowShowingTopAutoScale = ''; //Default: false
$nowShowingTopText = 'NOW SHOWING';
$nowShowingTopFontSize = '55'; //Default: 55 (px)
$nowShowingTopFontColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$nowShowingTopFontOutlineSize = '2'; //Default: 2 (px)
$nowShowingTopFontOutlineColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$nowShowingBottom = 'tagline'; //Default: title (title/summary/tagline/custom)
$nowShowingBottomText = '';
$nowShowingBottomAutoScale = ''; //Default: false
$nowShowingBottomFontSize = '25'; //Default: 25 (px)
$nowShowingBottomFontColor = '#FFFFFF'; //Default: #FFFFFF (White)
$nowShowingBottomFontOutlineSize = '2'; //Default: 2 (px)
$nowShowingBottomFontOutlineColor = '#FFFF00'; //Default: #FFFF00 (Yellow)

//Misc Configuration
$pmpDisplayProgress = 'Enabled'; //Default: Disabled
$pmpDisplayProgressSize = '5'; //Default: 5 (px)
$pmpDisplayProgressColor = '#FFFF00'; //Default: #FFFF00 (Yellow)
$pmpDisplayClock = 'Disabled'; //Default: Disabled (FUTURE)
$pmpBottomScroll = 'Disabled'; //Default: Disabled
$pmpBottomScrollSpeed = '1'; //Default: 1 (FUTURE)

**Comment by jeffreyswiggins** [comment] 2020-12-29 13:59
Also tested the **Coming Soon** and it still just shows a blank screen.  No text of even Coming Soon.

**Comment by MattsShack** [comment] 2020-12-29 14:58
The $plexServerMovieSection should be your library movie section number (not name)... I hope to fix this in a future release. 
I am will be reloading my raspberry pi this weekend from scratch and will test as well.

**Comment by jeffreyswiggins** [comment] 2020-12-29 15:09
Woh... where the fat rat to I get a section number?  Like in **SETTINGS LIBRARIES** the number of the main section that is all considered **Movies**?

**Comment by MattsShack** [comment] 2020-12-29 15:16
Open your plex web interface via the browser of your choice. 
Select your Movies section(s) from menu on the left.
Once section is loaded... Look towards the end of the URL in the browser. You should see something like "source=2". In this example my Movie section number is 2, however yours may be different. 

I hope this helps :)

**Comment by jeffreyswiggins** [comment] 2020-12-29 22:03
Okay i finally got back home and was able to switch from names to numbers for the Sections and that worked for it to start displaying the title and movie information however Posters still do not display on either Now Playing or Coming Soon.

Thanks so much for looking at this as I am very stoked to have this fun product working into my "theater"

**Comment by ZeroCoolGOS** [comment] 2020-12-29 22:53
@jeffreyswiggins 
I may have found your issue.
Go into your settings and unselect the "Cache Images" checkbox and see if that fixes the issue.

I do not know exactly how this option works.  @MattsShack could shed more light on it.

Once I had mine turned on I would get the text but not the posters.  As soon as I unselected it then my posters where fine again.

@Bboy486 have any of the things Matt and I suggested above also helped with your issue as well?

**Comment by jeffreyswiggins** [comment] 2020-12-30 00:18
@ZeroCoolGOS  when I unselect that I do not get posters and my text now disappears back to a blank screen

**Comment by Bboy486** [comment] 2020-12-30 00:25
@ZeroCoolGOS sorry for the delay. 

Cached Images
This was already unchecked for me.

in the config.php (I see two one in ~/Plex-Movie-Poster-Display and another in /var/www/html/Plex-Movie-Poster-Display) is it not saving the settings I added into the admin. I can manually add it but not sure which location?

  $pmpClearImageCache = 'Yes'; //Default Yes
  $pmpImageSpeed = '30'; //Default 30 Seconds
  $pmpPosterDir = 'cache/posters/'; //Default cache/posters/ (FUTURE)
  $pmpCustomDir = 'cache/custom/'; //Default cache/custom/ (FUTURE)

  //Server Configuration
  $plexServer = '';
  $plexToken = '';
  $plexServerMovieSection = '';

  //Cleint Configuration
  $plexClient = '';

**Comment by ZeroCoolGOS** [comment] 2020-12-30 00:30
@Bboy486 

It should be the "/var/www/html/Plex-Movie-Poster-Display" as that should be where the site is being hosted.

You should not need to make any direct modifications to the config.php file.

Your config file is not being updated at all after updates to the admin page?  Is that correct?

**Comment by ZeroCoolGOS** [comment] 2020-12-30 00:32
> @ZeroCoolGOS when I unselect that I do not get posters and my text now disappears back to a blank screen

That is odd.  I will take your config and try and apply to my system and see if I can recreate.  I was only able to have a blank page when cache was enabled.

**Comment by Bboy486** [comment] 2020-12-30 00:37
> Your config file is not being updated at all after updates to the admin page? Is that correct?

That is correct. I have it updated in the .admin.php but the config was empty. I did manually update the config file in var but the issue of the posters not showing on idle remains. 

This is my manual config


  //PMPD Config
  $pmpConfigVersion = '2';
  $pmpUsername = 'xxx';
  $pmpPassword = 'xxx';
  $pmpClearImageCache = 'Yes'; //Default Yes
  $pmpImageSpeed = '30'; //Default 30 Seconds
  $pmpPosterDir = 'cache/posters/'; //Default cache/posters/ (FUTURE)
  $pmpCustomDir = 'cache/custom/'; //Default cache/custom/ (FUTURE)

  //Server Configuration
  $plexServer = 'IP';
  $plexToken = '...';
  $plexServerMovieSection = 'Movies,Disney Pixar,Children Movies,Christmas Movies'

  //Cleint Configuration
  $plexClient = 'IP';
  $plexClientName = 'Plex Web';

  //Custom Image
  $customImageEnabled = 'Disabled'; //Default Disabled
  $customImage = '';
  $customTopText = 'CUSTOM TOP TEXT';
  $customTopFontSize = '55'; //Default 55
  $customTopFontColor = '#FFFFFF'; //Default #FFFFFF (White)
  $customTopFontOutlineSize = '2'; //Default 2p
  $customTopFontOutlineColor = '#FFFF00'; //Default #FFFF00 (Yellow)
  $customBottomText = 'CUSTOM BOTTOM TEXT';
  $customBottomFontSize = '25'; //Default 25
  $customBottomFontColor = '#FFFFFF'; //Default #FFFFFF (White)

  //Coming Soon Config
  $comingSoonTopText = 'COMING SOON';
  $comingSoonTopFontSize = '55'; //Default 55
  $comingSoonTopFontColor = '#FFFF00'; //Default Yellow
  $comingSoonTopFontOutlineColor = '#FFFF00'; //Default Yellow
  $comingSoonTopFontOutlineSize = '2'; //Default 2
  $comingSoonBottomText = 'www.mattsshack.com';
  $comingSoonBottomFontSize = '55'; //Default 55

**Comment by ZeroCoolGOS** [comment] 2020-12-30 00:43
> > Your config file is not being updated at all after updates to the admin page? Is that correct?
> 
> That is correct. I have it updated in the .admin.php but the config was empty. I did manually update the config file in var but the issue of the posters not showing on idle remains.
@Bboy486 
That is interesting.  We will first want to address that issue before we tackle the poster not showing on idle.

If the config is not updating at all then can you try to re-apply the permissions on the folder?  It could be that the admin page does not have permissions to write to the config.php.

Permissions
sudo chmod -R 774 /var/www/html/
sudo chown -R pi:www-data /var/www/html/

**Comment by Bboy486** [comment] 2020-12-30 00:45
Sure. I had that already set but did it again. It looks to be updating.

Edit- spoke too soon. It is not updating from the admin.


admin - https://prnt.sc/wcn4ll
display (the yellow was what I had it before I saved) https://prnt.sc/wcn4uz

**Comment by ZeroCoolGOS** [comment] 2020-12-30 00:55
> Sure. I had that already set but did it again. It looks to be updating.
> 
> Edit- spoke too soon. It is not updating from the admin.
> 
> admin - https://prnt.sc/wcn4ll
> display (the yellow was what I had it before I saved) https://prnt.sc/wcn4uz

Ok.  So are some values saving but others not?  Like can you set the different text in the custom filed, save and refresh the admin page and it shows up?

**Comment by Bboy486** [comment] 2020-12-30 00:56
Yes so Now Showing Top Font Color - color change works in the admin 

Now Showing Top Font Outline Size & Now Showing Top Font Outline Color do not

**Comment by Bboy486** [comment] 2020-12-30 00:58
I deleted all files and reinstalled them.  Still no writing to the config.php file (I ran the permissions again as well).

**Comment by ZeroCoolGOS** [comment] 2020-12-30 01:10
@Bboy486 
Ok.  So I can recreate the issue with the "Outline Size" and "Outline Color" not displaying correctly and will need to be worked on to fix this issue.

For any other custom text fields, I would suggest to updating to the dev branch as it has a bunch of admin fixes already.

If from a clean install you should not have the Plex Token.  So when you go into the admin page you are providing the token and the ip of your plex server and it is not stored at all in the config so you are always modifying the config.php manually even for the IP and token?

**Comment by Bboy486** [comment] 2020-12-30 01:25
Yes. I am modifying the config. What is the command to update to the dev branch?

**Comment by ZeroCoolGOS** [comment] 2020-12-30 01:28
> Yes. I am modifying the config. What is the command to update to the dev branch?

git checkout dev

That should get you into the dev branch and then you can do your install.

**Comment by Bboy486** [comment] 2020-12-30 01:33
that wouldn't work for raspian right?

**Comment by ZeroCoolGOS** [comment] 2020-12-30 01:35
> that wouldn't work for raspian right?

Well it depends on how your getting the code.  Are you using GIT to clone down the repo or are you just downloading the files?

**Comment by Bboy486** [comment] 2020-12-30 01:38
cd /your_preferred_directory 
sudo git clone https://github.com/MattsShack/Plex-Movie-Poster-Display.git

**Comment by ZeroCoolGOS** [comment] 2020-12-30 01:41
> cd /your_preferred_directory
> sudo git clone https://github.com/MattsShack/Plex-Movie-Poster-Display.git

then cd into the "Plex-Movie-Poster-Display" directory
then git checkout dev

Then you should be in the dev branch
if you type "git branch -a" you should see something like "* dev"

**Comment by Bboy486** [comment] 2020-12-30 20:42
All set-up. Coming soon issue remains.

**Comment by ZeroCoolGOS** [comment] 2020-12-30 20:53
> All set-up. Coming soon issue remains.

I have found the issue with the Text color and size outline issue and should have a fix ready today.  Once we have that one closed then we can try and address the next issue.

As there has been a bunch of back and forth within this change I want to just make sure we are clear with the issues:
1. Coming Soon & Now Playing Text outline changes not applying correctly. - Fix coming soon (Attached to bug #14 )
2. No Posters are displaying when not playing any movies through the Client
3. Posters not working when using library name ("Movie", "TV Show") - Future Enhancement. Better documentation has been created for the information required from the Plex server.  Included in Pull Request #13 

@Bboy486 @jeffreyswiggins please let me know if I have missed any issues that we have identified.  If there are any more issues let me know.  The best way to address these issues will be to break them out into separate bugs to track.  Once I have the comprehensive list then I can create the bug list and have you guys fill in the details.

Thank you,

**Comment by Bboy486** [comment] 2020-12-30 21:36
Missing Admin does not write/save to config even with permissions set.

**Comment by ZeroCoolGOS** [comment] 2020-12-31 00:29
@Bboy486 

The latest dev branch code now has the fix for the text outline issue.

Looking back at your config posted. You still have text in your config plexServerMovieSection.

$plexServerMovieSection = 'Movies,Disney Pixar,Children Movies,Christmas Movies'

A few msgs above that @MattsShack has indicated that this needs to be a numeric value.  Have you updated these to be a numeric value instead of the "text" and your still having the issue?

That is one of the ways I was able to recreate no posters or anything when plex is not playing from the client.

**Comment by Bboy486** [comment] 2021-01-01 06:47
Yes I changed them 

$plexServerMovieSection = '1,4,6,3,8,9,10';
$cacheEnabled = ''; //Default true

That brings the photos in (although some are screenshots and not poster art). 
https://www.awesomescreenshot.com/video/2233744?key=127c919cc97324e8b940bdc3156c8fda
But the bug with the text is there (on refresh or launching the site).

**Comment by Bboy486** [comment] 2021-01-01 17:30
Sample of image showing screenshot and not poster. https://prnt.sc/we8fnq

**Comment by MattsShack** [comment] 2021-01-01 18:03
Cached images should now be fixed in the dev branch.

**Comment by ZeroCoolGOS** [comment] 2021-01-01 21:01
@Bboy486 

The sample image might have to do with what image your Plex server has assigned to that particular movie.  I believe this system is just pulling the image that Plex is serving up.  Can you validate that the poster is correct in your Library for these particular instances?

As for the "Font Oversize" issue.  I believe that was fixed in the dev branch.  Are you using the latest code from the dev branch?
If not, I would recommend that you update as that should have that fix and a bunch of other fixes.

Let us know if that resolves that issue.

**Comment by Bboy486** [comment] 2021-01-02 06:43
No I thought I had the dev branch pulled in but I received this error:


pi@raspberrypi:/var/www/html/Plex-Movie-Poster-Display $ git checkout dev

fatal: not a git repository (or any of the parent directories): .git
pi@raspberrypi:/var/www/html/Plex-Movie-Poster-Display $

**Comment by ZeroCoolGOS** [comment] 2021-01-02 08:06
> No I thought I had the dev branch pulled in but I received this error:
> 
> pi@raspberrypi:/var/www/html/Plex-Movie-Poster-Display $ git checkout dev
> 
> fatal: not a git repository (or any of the parent directories): .git
> pi@raspberrypi:/var/www/html/Plex-Movie-Poster-Display $

When doing a git clone or pull you should not be using it directly in the NGinX folder.

It should be done from a separate directory and then the files should be copied into the "/var/www/html" folder.

This could be partially the cause of the admin update that you are having.  

I would recommend that you run your git clone from your download folder and copy the files over to the "/var/www/html" folder as per the instructions.

We will look at streamlining the install process in a future update.

Also if your familiar with docker, this project can also be used in a docker image.

**Comment by MattsShack** [comment] 2021-01-02 16:16
Remember that your config will be overwritten. So be sure to save you Plex Token etc. for easier setup.

**Master Branch**
cd /your_preferred_git_directory 
sudo git clone --branch master https://github.com/MattsShack/Plex-Movie-Poster-Display.git
cd Plex-Movie-Poster-Display
sudo cp -R * /var/www/html

**Dev Branch**
cd /your_preferred_git_directory
sudo git clone --branch dev https://github.com/MattsShack/Plex-Movie-Poster-Display.git
cd Plex-Movie-Poster-Display
sudo cp -R * /var/www/html

**Comment by Bboy486** [comment] 2021-01-06 03:43
@ZeroCoolGOS I have Plex-Movie-Poster-Display in my home/pi/ folder and I copied it to /var/www/html/Plex-Movie-Poster-Display. I do not use docker. 

Anyway I deleted the sub folder and copied into www/html. I am on the dev version now.

**Comment by ZeroCoolGOS** [comment] 2021-01-07 20:04
@Bboy486 
Now that you have been running the dev branch for the past few days.  How has your system been running?
What issues have you ran into lately and what issues have since resolved?

**Comment by jeffreyswiggins** [comment] 2021-01-07 20:16
I have been running the latest dev branch I downloaded about 24 hours ago for the last 24 hours.  Not seen any issues and everything I have tested works as expected, I ha e tested the SSL yet because I haven’t read on what is needed for that

**Comment by Bboy486** [comment] 2021-01-09 00:01
> @Bboy486 
> Now that you have been running the dev branch for the past few days.  How has your system been running?
> What issues have you ran into lately and what issues have since resolved?

The dev branch has been great. No issues to report!

**Comment by ZeroCoolGOS** [comment] 2021-02-20 23:35
@MattsShack ,
It looks like the issues have been addressed for this ticket.  

Unless @Bboy486  and @jeffreyswiggins object, I believe this ticket can be closed.

Any new issues can be logged in a new ticket.

**Comment by Bboy486** [comment] 2021-02-21 18:18
Yes thank you! Fixed on dev branch.

**Closed as completed** 2021-02-22 03:10 UTC
